### ISSUE TITLE
Safety/Security issue!

### ISSUE THREAD

**Issue by Oxides** [ChrisAntaki/plugins-and-mimetypes-firefox#2]
You need to whitelist this page.
https://www.mozilla.org/en-US/plugincheck/
Firefox redirects to this page when you do tools/addons/plugins/checktoseeifpluginsareuptodate

**Comment by ChrisAntaki** [comment]
Sadly, it looks like Mozilla broke the privacy feature that made this plugin possible. https://bugzilla.mozilla.org/show_bug.cgi?id=1169945
