### ISSUE TITLE
New icons are too large

### ISSUE THREAD

**Issue by dkasak** [ChrisAntaki/plugins-and-mimetypes-firefox#5]
The new icons are [much larger](http://i.imgur.com/x783jLI.png) than other Firefox icons (both standard icons and common extension icons) which takes up space, enlargens the toolbar they are placed in and makes it look irregular. Any chance this could be revised to a more standard size?

Other than that, the new icons look much cleaner than the previous ones (if a bit less fun). :D

**Comment by ChrisAntaki** [comment]
Thanks for the feedback, @dkasak. Would you be interested in posting a screenshot of the issue? I haven't been able to reproduce it on my end.

**Comment by dkasak** [comment]
The words "much larger" in my previous comment are a (cropped) screenshot of the issue. Did you miss this or do you want a full-screen screenshot perhaps?

**Comment by ChrisAntaki** [comment]
Hehe, I missed that link. Could I ask what version of Firefox you're using, and which OS?

**Comment by dkasak** [comment]
Firefox 37.0.1 on Arch Linux. I just checked to see if it happens on a clean profile and it does. However, I noticed the icon size is normal if placed on the menu bar but oversized if placed on a bookmarks toolbar.

**Comment by careca1970** [comment]
Hi there!
I have same problem. Once you place this icon in the addons bar, the bar gets resized to its bigger size.
Many thanks in advance!

**Comment by ChrisAntaki** [comment]
Thanks for pointing this out @dkasak & @careca1970! I just uploaded a new version of the plugin with the icon sizes fixed.

**Comment by dkasak** [comment]
This fixed the issue for me so I'll close it. If @careca1970 is by any chance still experiencing it with the new version, he can reopen it.

**Comment by ChrisAntaki** [comment]
Glad to hear it @dkasak
